---
- hosts: all
  become: true
  tasks:
    - name: install dependency
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - python3-setuptools
        - software-properties-common
    - name: Install bottle python package
      ansible.builtin.pip:
        name: bottle
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Pull default Docker image
      community.docker.docker_image:
        name: redis:latest
        source: pull
